### ISSUE TITLE
Order와 OrderDetail 시간 차이

### ISSUE THREAD

**Issue by kwangddang** [woowa-techcamp-2022/android-banchan-01#204]
## 📌  Issue
- OrderDetail에 들어갔을 때는 배송완료가 되어 있지만 Order에서는 배송준비중이 되어 있습니다.

**Comment by hansh0101** [comment]
시스템 상의 약간의 시간적 오차에서 발생하는 문제.

OrderDetail에서 표시하는 기준은 현재 시간 - DB에 아이템이 삽입된 시간 >= 10초,
OrderList에서 표시하는 기준은 DB에 아이템 삽입이 성공하고 AlarmManager를 통해 Notification을 생성한 시간으로부터 10초가 지나 Notification이 발생했는지 이기 때문.

별도의 Fix 처리 없음.
